# Generated by Django 6.0.5 on 2026-05-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calory_counter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfomodel',
            name='bmr',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='basicinfomodel',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
